server:
  port: 8888
spring:
  application:
    name: config
  config:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sergeivisotsky/airport-management-config
          clone-on-start: true
          search-paths: "{application}" # application config file or directory name
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    status-page-url-path: http://localhost:${server.port}/actuator/info
    health-check-url-path: http://localhost:${server.port}/actuator/health
    home-page-url: http://localhost:${server.port}
    lease-renewal-interval-in-seconds: 10 # intervalSeconds between subsequent heartbeats sent to Eureka server
    lease-expiration-duration-in-seconds: 20 # time that Eureka server waits since it received last heartbeat before it can evict this instance
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10 # how often to fetch the registry from Eureka server
    instance-info-replication-interval-seconds: 10 # how often to replicate instance changes to be replicated to Eureka server
    serviceUrl:
      defaulZone: http://localhost:8761/eureka/
logging:
  file: C:/tmp/config.log
  level:
    ROOT: INFO
    org:
      sergei:
        config: DEBUG
