language: java

jdk:
- oraclejdk8
- oraclejdk9
#- oraclejdk11
- openjdk8
- openjdk9
- openjdk10
#- openjdk11

services:
- mysql

before_install:
- chmod +x mvnw

branches:
  only:
  - master
  - develop