version: '3.7'
services:
  config-service:
    container_name: config-service
    build:
      context: config-service
      dockerfile: Dockerfile
    image: config-service:latest
    expose:
      - 8888
    networks:
      - spring-cloud-network
    volumes:
      - flight-reservation-config-service:/var/lib/flight-reservation/config-service
    logging:
      driver: json-file
  eureka-service:
    container_name: eureka-service
    build:
      context: eureka-service
      dockerfile: Dockerfile
    image: eureka-service:latest
    expose:
      - 8888
    networks:
      - spring-cloud-network
    volumes:
      - flight-reservation-eureka-service:/var/lib/flight-reservation/eureka-service
    logging:
      driver: json-file
    command: mvn clean package spring-boot:repackage
  auth-service:
    container_name: auth-service
    build:
      context: auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://localhost:8079"}}}}'
    expose:
      - 9094
    ports:
      - 9094:9094
    networks:
      - spring-cloud-network
    volumes:
      - flight-reservation-auth-service:/var/lib/flight-reservation/auth-service
    links:
      - config-service:config-service
      - eureka-service:eureka-service
    depends_on:
      - config-service
      - eureka-service
    logging:
      driver: json-file
    command: mvn clean package spring-boot:repackage
  reservation-service:
    container_name: reservation-service
    build:
      context: reservation-service
      dockerfile: Dockerfile
    image: reservation-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://localhost:8079"}}}}'
    expose:
      - 9091
    ports:
      - 9091:9091
    networks:
      - spring-cloud-network
    volumes:
      - flight-reservation-reservation-service:/var/lib/flight-reservation/reservation-service
    links:
      - config-service:config-service
      - eureka-service:eureka-service
    depends_on:
      - config-service
      - eureka-service
    logging:
      driver: json-file
    command: mvn clean package spring-boot:repackage
  ticket-service:
    container_name: ticket-service
    build:
      context: ticket-service
      dockerfile: Dockerfile
    image: ticket-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://localhost:8079"}}}}'
    expose:
      - 9092
    ports:
      - 9092:9092
    networks:
      - spring-cloud-network
    volumes:
      - flight-reservation-ticket-service:/var/lib/flight-reservation/ticket-service
    links:
      - config-service:config-service
      - eureka-service:eureka-service
    depends_on:
      - config-service
      - eureka-service
    logging:
      driver: json-file
    command: mvn clean package spring-boot:repackage
  doc-service:
    container_name: doc-service
    build:
      context: doc-service
      dockerfile: Dockerfile
    image: doc-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://localhost:8079"}}}}'
    expose:
      - 9093
    ports:
      - 9093:9093
    networks:
      - spring-cloud-network
    volumes:
      - flight-reservation-doc-service:/var/lib/flight-reservation/doc-service
    links:
      - config-service:config-service
      - eureka-service:eureka-service
    depends_on:
      - config-service
      - eureka-service
    logging:
      driver: json-file
    command: mvn clean package spring-boot:repackage
  zuul-gateway:
    container_name: zuul-gateway
    build:
      context: zuul-gateway
      dockerfile: Dockerfile
    image: zuul-gateway:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://localhost:8079"}}}}'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - spring-cloud-network
    volumes:
      - flight-reservation-zuul-gateway:/var/lib/flight-reservation/zuul-gateway
    links:
      - config-service:config-service
      - eureka-service:eureka-service
    depends_on:
      - config-service
      - eureka-service
    logging:
      driver: json-file
    command: mvn clean package spring-boot:repackage
  report-service:
    container_name: report-service
    build:
      context: report-service
      dockerfile: Dockerfile
    image: report-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "https://localhost:9095"}}}}'
    expose:
      - 9095
    ports:
      - 9095:9095
    networks:
      - spring-cloud-network
    volumes:
      - flight-reservation-zuul-gateway:/var/lib/flight-reservation/report-service
    links:
      - config-service:config-service
      - eureka-service:eureka-service
    depends_on:
      - config-service
      - eureka-service
    logging:
      driver: json-file
    command: mvn clean package spring-boot:repackage
networks:
  spring-cloud-network:
    driver: bridge
volumes:
  flight-reservation-config-service:
    external: true
  flight-reservation-eureka-service:
    external: true
  flight-reservation-auth-service:
    external: false
  flight-reservation-reservation-service:
    external: false
  flight-reservation-ticket-service:
    external: false
  flight-reservation-doc-service:
    external: false
  flight-reservation-zuul-gateway:
    external: false