#!groovy

def  POM_LOCATION = '-f auth/pom.xml'
pipeline {
    agent any
    tools {
        maven 'maven_3_6_1'
    }
    stages {
        stage('Compilation') {
            steps {
                echo '-=- compiling project -=-'
                sh "mvn ${POM_LOCATION} clean compile -DskipTests=true"
            }
        }
        stage('Testing') {
            steps {
                echo '-=- execute unit tests -=-'
                sh "mvn ${POM_LOCATION} test"
            }
        }
        stage('Installation') {
            steps {
                echo '-=- installing project -=-'
                sh "mvn ${POM_LOCATION} clean install -DskipTests=true"
            }
        }
        stage('Packaging') {
            steps {
                echo '-=- packaging project -=-'
                sh "mvn ${POM_LOCATION} package -DskipTests=true"
            }
        }
//        stage('Code inspection & quality gate') {
//            steps {
//                withSonarQubeEnv('sonar') {
//                    echo '-=- run code inspection & check quality gate -=-'
//                    sh "mvn ${POM_LOCATION} sonar:sonar " +
//                            "-Dsonar.host.url=http://79.135.149.36:9000 " +
//                            "-Dsonar.login=44f87ea38cda252594b6c8215e097fc39a0f58d0"
//                }
//            }
//        }
    }
}