server:
  port: 8085
spring:
  application:
    name: flight-reservation
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flight_reservation?allowPublicKeyRetrieval=true&useSSL=false
    username: flight
    password: flight
    initialization-mode: embedded
  jpa:
    properties:
      hibernate:
      show_sql: true
      hbm2ddl:
      auto: update
      generate-ddl: true
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
