spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flight_reservation?allowPublicKeyRetrieval=true&useSSL=false
    username: flight
    password: flight
    data: classpath:schema.sql
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
        generate-ddl: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
security:
  oauth2:
    jdbc:
      tokenstore-url: jdbc:mysql://localhost:3306/flight_reservation_oauth?allowPublicKeyRetrieval=true&useSSL=false