server:
  port: 8080
spring:
  application:
    name: gateway
eureka:
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
    status-page-url-path: http://localhost:${server.port}/actuator/info
    health-check-url-path: http://localhost:${server.port}/actuator/health
    home-page-url: http://localhost:${server.port}
    lease-renewal-interval-in-seconds: 10 # intervalSeconds between subsequent heartbeats sent to Eureka server
    lease-expiration-duration-in-seconds: 20 # time that Eureka server waits since it received last heartbeat before it can evict this instance
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10 # how often to fetch the registry from Eureka server
    instance-info-replication-interval-seconds: 10 # how often to replicate instance changes to be replicated to Eureka server
    serviceUrl:
      defaulZone: http://localhost:8761/eureka/
management:
  endpoint:
    health:
      show-details: always
zuul:
  ssl-hostname-validation-enabled: false # No recommended in real production applications
  routes:
    service-resource:
      path: /service/**
      service-id: service-resource
      url: http://localhost:8084
      sensitive-headers: true
    auth:
      path: /auth/**
      service-id: auth
      url: http://localhost:8082
      strip-prefix: false
      sensitive-headers: true
    reservation:
      path: /reservation/**
      service-id: reservation
      url: http://localhost:8083
      strip-prefix: false
      sensitive-headers: true
    tickets:
      path: /tickets/**
      service-id: tickets
      url: http://localhost:8086
      strip-prefix: false
      sensitive-headers: true
    reports:
      path: /reports/**
      service-id: reports
      url: http://localhost:8089
      strip-prefix: false
      sensitive-headers: true