server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: false
zuul:
  ssl-hostname-validation-enabled: false # No recommended in real production applications
  routes:
    auth:
      path: /auth/**
      service-id: auth
      url: http://localhost:8082
      sensitive-headers: true
    reservation:
      path: /reservation/**
      service-id: reservation
      url: http://localhost:8083
      sensitive-headers: true
    tickets:
      path: /tickets/**
      service-id: tickets
      url: http://localhost:8086
      sensitive-headers: true
    reports:
      path: /reports/**
      service-id: reports
      url: http://localhost:8089
      sensitive-headers: true
    manager:
      path: /manager/**
      service-id: manager
      url: http://localhost:8088
      sensitive-headers: true

management:
  endpoint:
    health:
      show-details: always
logging:
  file: C:/tmp/gateway.log
  level:
    ROOT: INFO
    org:
      sergei:
        gateway: DEBUG