server:
  port: 8086
  servlet:
    context-path: /docs
spring:
  application:
    name: doc-service
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaulZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
swagger:
  config:
    refreshrate: 5000