server:
  port: 8762
spring:
  application:
    name: zuul-gateway
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaul-zone: http://localhost:8761/eureka
management:
  endpoint:
    routes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  routes:
    flight-reservation:
      serviceId: flight-reservation