server:
  port: 8080
spring:
  application:
    name: zuul-gateway
eureka:
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
    status-page-url-path: http://localhost:${server.port}/actuator/info
    health-check-url-path: http://localhost:${server.port}/actuator/health
    home-page-url: http://localhost:${server.port}
    lease-renewal-interval-in-seconds: 10 # intervalSeconds between subsequent heartbeats sent to Eureka server
    lease-expiration-duration-in-seconds: 20 # time that Eureka server waits since it received last heartbeat before it can evict this instance
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10 # how often to fetch the registry from Eureka server
    instance-info-replication-interval-seconds: 10 # how often to replicate instance changes to be replicated to Eureka server
    serviceUrl:
      defaulZone: http://localhost:8761/eureka/
management:
  endpoint:
    health:
      show-details: always
zuul:
  ssl-hostname-validation-enabled: false # No recommended in real production applications
  routes:
    service-resource:
      path: /service-api/**
      service-id: service-resource
      url: http://localhost:8084
      sensitive-headers: true
    doc-service:
      path: /docs/**
      service-id: doc-service
      url: http://localhost:8085
      strip-prefix: false
      sensitive-headers: true
    auth-service:
      path: /auth-api/**
      service-id: auth-service
      url: http://localhost:8082
      strip-prefix: false
      sensitive-headers: true
    reservation-service:
      path: /reservation-api/**
      service-id: reservation-service
      url: http://localhost:8083
      strip-prefix: false
      sensitive-headers: true
    ticket-service:
      path: /ticket-api/**
      service-id: ticket-service
      url: http://localhost:8086
      strip-prefix: false
      sensitive-headers: true
    report-service:
      path: /report-api/**
      service-id: report-service
      url: http://localhost:8089
      strip-prefix: false
      sensitive-headers: true