server:
  port: 8083
spring:
  application:
    name: zuul-server
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaul-zone: http://localhost:8761/eureka/
management:
  endpoint:
    routes:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"