server:
  port: 8082
spring:
  application:
    name: auth
  cloud:
    discovery:
      enabled: true

# DataSource configuration
datasource:
  jdbc-url: jdbc:postgresql://localhost:5432/flight_reservation
  type: com.zaxxer.hikari.HikariDataSource
  username: flight
  password: flight

# security specific configuration
security:
  oauth2:
    access-token-uri: http://localhost:8080/auth/oauth/token
    user-authorization-uri: http://localhost:8080/auth/oauth/authorize

management:
  endpoints.web.exposure.include: "info, health, metrics, configprops, env, prometheus"
logging:
  file: C:/tmp/auth.log
  level:
    ROOT: INFO
    org:
      sergei:
        auth: DEBUG