server:
  port: 8082

spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

# DataSource configuration
datasource:
  jdbc-url: jdbc:postgresql://localhost:5432/flight_reservation
  type: com.zaxxer.hikari.HikariDataSource
  username: flight
  password: flight

logging:
  file: C:/tmp/auth.log
  level:
    ROOT: INFO
    org:
      sergei:
        auth: DEBUG