server:
  port: 8083

# Spring specific configuration
spring:
  application:
    name: reservation
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Remote service endpoints
manager:
  route-uri: http://localhost:8088/getRouteById

# Feign client properties
feign:
  route-url: http://localhost:8088/

# DataSource configuration
datasource:
  jdbc-url: jdbc:postgresql://localhost:5432/flight_reservation
  type: com.zaxxer.hikari.HikariDataSource
  username: flight
  password: flight

management:
  endpoints.web.exposure.include: "info, health, metrics, configprops, env, prometheus"

logging:
  file: C:/tmp/reservation.log
  level:
    ROOT: INFO
    org:
      sergei:
        reservation: DEBUG