server:
  port: 8098

# Spring specific configuration
spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# DataSource configuration
datasource:
  jdbc-url: jdbc:postgresql://localhost:5432/am_cargo
  type: com.zaxxer.hikari.HikariDataSource
  username: flight
  password: flight

# Logging configuration
logging:
  file: C:/tmp/cargo.log
  level:
    ROOT: INFO
    org:
      sergei:
        cargo: DEBUG
