spring:
  application:
    name: processor
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# Monitoring endpoints
management:
  endpoints.web.exposure.include: "info, health, metrics, configprops, env, prometheus"