apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config
  namespace: prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: config
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: accept
                    operator: DoesNotExist
      securityContext:
        runAsUser: 1002
      containers:
        - image: sergeivisotsky/airport-management:config
          name: config
          ports:
            - containerPort: 8888
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          env:
            - name: FORCE_K8S_REDEPLOY
              value: 'CI_BUILD_ID'
            - name: vault.token
              value: 'VAULT_TOKEN_DB'
            - name: vault.secret
              valueFrom:
                secretKeyRef:
                  name: vault-crt
                  key: vault-crt
            - name: spring.profiles.active
              value: 'prod'
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 250m
          securityContext:
            allowPrivilegeEscalation: false
        - image: jaegertracing/jaeger-agent
          name: jaeger-agent
          ports:
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
          args: ["--collector.host-port=jaeger-collector.tracing:14267"]
      imagePullSecrets:
        - name: airport-management
      restartPolicy: Always
