pipeline {

    agent any
    tools {
        maven 'maven_3_6_1'
    }

    stages {

        stage('Compilation') {
            steps {
                echo '-=- compiling project -=-'
                sh 'mvn -f config/pom.xml clean compile -DskipTests=true'
            }
        }
        stage('Testing') {
            steps {
                echo '-=- execute unit tests -=-'
                sh 'mvn -f config/pom.xml test'
            }
        }
        stage('Installation') {
            steps {
                echo '-=- installing project -=-'
                sh 'mvn -f config/pom.xml clean install -DskipTests=true'
            }
        }
        stage('Packaging') {
            steps {
                echo '-=- packaging project -=-'
                sh 'mvn -f config/pom.xml package -DskipTests=true'
            }
        }
        stage('Code inspection & quality gate') {
            steps {
                withSonarQubeEnv('sergei-sonar') {
                    echo '-=- run code inspection & check quality gate -=-'
                    sh 'mvn -f config/pom.xml sonar:sonar ' +
                            '-Dsonar.host.url=http://79.135.149.36:9000 ' +
                            '-Dsonar.login=b18abeedf7353813275264a410d0acbc771219cd'
                }
            }
        }
    }
}