spring:
  application:
    name: payment
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# Monitoring endpoints
management:
  endpoints.web.exposure.include: "info, health, metrics, configprops, env, prometheus"

# Adds some information into the Actuator info page
info:
  app:
    name: Payment
    version: 1.0
    descripton: Service to perform scheduled flight payment