server:
  port: 8088

# Spring specific configuration
spring:
  application:
    name: manager
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# DataSource configuration
datasource:
  jdbc-url: jdbc:postgresql://localhost:5432/flight_reservation
  type: com.zaxxer.hikari.HikariDataSource
  username: flight
  password: flight

management:
  endpoints.web.exposure.include: "info, health, metrics, configprops, env, prometheus"

logging:
  file: C:/tmp/manager.log
  level:
    ROOT: INFO
    org:
      sergei:
        manager: DEBUG

info:
  app:
    name: Management service
    version: 1.0
    profile: dev
    descripton: Service to perform airport management operations e.g. save aircraft, pilot, calendar and other administrative data
