server:
  port: 8088

# Spring specific configuration
spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# DataSource configuration
datasource:
  jdbc-url: jdbc:postgresql://localhost:5432/am_manager
  type: com.zaxxer.hikari.HikariDataSource
  username: flight
  password: flight

logging:
  file: C:/tmp/manager.log
  level:
    ROOT: INFO
    org:
      sergei:
        manager: DEBUG
