server:
  port: 8083

# Spring specific configuration
spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# DataSource configuration
datasource:
  jdbc-url: jdbc:postgresql://localhost:5432/am_booking
  type: com.zaxxer.hikari.HikariDataSource
  username: flight
  password: flight

feign:
  manager-url: http://localhost:8088

logging:
  file: C:/tmp/booking.log
  level:
    ROOT: INFO
    org:
      sergei:
        booking: DEBUG
