server:
    port: 8089

# Spring specific configuration
spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

feign:
  manager-url: http://localhost:8088
  booking-url: http://localhost:8083

# Logging configuration
logging:
  file: C:/tmp/orchestration.log
  level:
    ROOT: INFO
    org:
      sergei:
        template: DEBUG
