def POM_LOCATION = '-f reservation/pom.xml'
pipeline {
    agent any
    tools {
        maven 'maven_3_6_1'
    }
    stages {
        stage('Code inspection & quality gate') {
            steps {
                withSonarQubeEnv('sonar') {
                    echo '-=- run code inspection & check quality gate -=-'
                    sh "${SonarScanner 4.0}/bin/sonar-scanner"
                }
            }
        }
        stage('Compilation') {
            steps {
                echo '-=- compiling project -=-'
                sh "mvn ${POM_LOCATION} clean compile -DskipTests=true"
            }
        }
        stage('Testing') {
            steps {
                echo '-=- execute unit tests -=-'
                sh "mvn ${POM_LOCATION} test"
            }
        }
        stage('Installation') {
            steps {
                echo '-=- installing project -=-'
                sh "mvn ${POM_LOCATION} clean install -DskipTests=true"
            }
        }
        stage('Packaging') {
            steps {
                echo '-=- packaging project -=-'
                sh "mvn ${POM_LOCATION} package -DskipTests=true"
            }
        }
    }
}
