server:
  port: 8761
  http:
    port: 9095
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: eureka-service/src/main/resources/tls/keystore.p12
    key-store-password: keyStoreSecret
    key-alias: localhost
spring:
  application:
    name: eureka-service
eureka:
  instance:
    hostname: localhost
    secure-port-enabled: true
    secure-port: ${server.port}
    non-secure-port-enabled: false
    homePageUrl: http://${eureka.instance.hostname}:${server.port}
    metadata-map:
      hostname: ${eureka.instance.hostname}
      securePort: ${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaulZone: http://localhost:8761/eureka/