spring:
  application:
    name: reports
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# Monitoring endpoints
management:
  endpoints.web.exposure.include: "info, health, metrics, configprops, env, prometheus"

# Adds some information into the Actuator info page
info:
  app:
    name: Reports
    version: 1.0
    descripton: Reports service to perform airport management facts